dist: trusty
sudo: required
language: c

addons:
  sonarqube:
    branches:
      - master
      - dev

before_install:
  - sudo apt-get update -qq

script:
  - echo hello

notifications:
  slack: camflow:T3Umf9cAIwKnaxFEkjeZV7RM
